$color = rgba(5, 19, 5, 1)
$inner_color = rgba(5, 19, 5, 0.66)
$outer_color = rgba(205, 152, 205, 1)
$font_color = rgba(183, 210, 178, 1)
$placeholder_color = rgba(183, 210, 178, 0.7)
$check_color = rgba(167, 210, 162, 1)
