background            #051305
foreground            #b7d2b2

# black
color0  #051305
color8  #5aa45a

# red
color1  #d18585
color9  #daaaaa

# green
color2  #82bb7c
color10 #b8dbb5

# yellow
color3  #8fbf87
color11 #bedcb9

# blue
color4  #8d8dc9
color12 #bbbbe1

# magenta
color5  #cd98cd
color13 #e3c0e3

#cyan
color6  #a7d2a2
color14 #c7e5c4

#white
color7  #b7d2b2
color15 #89b981


